AniLiteWebSite/Controllers/HelperController.cs
using AniLiteWebSite.Core;
using AniLiteWebSite.Core.DataBase.Model;
using AniLiteWebSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace AniLiteWebSite.Controllers
{
    public class HelperController : MyController
    {
        //
        // GET: /Helper/

        public ActionResult AuthWidget()
        {
            if (ControllerContext.ParentActionViewContext == null) RedirectToAction("Error","Error");
            if(User == null)
            {
                ViewData["AuthURI"] = AuthLink;
                return View();
            }
            var rd = ControllerContext.ParentActionViewContext.RouteData;
            ViewData["PAction"] = rd.GetRequiredString("action") as string;
            ViewData["PController"] = rd.GetRequiredString("controller") as string;
            return View(User);
        }

        public ActionResult MainMenu()
        {
            if (ControllerContext.ParentActionViewContext == null)
            {
                return RedirectToAction("Error", "Error");
            }
            else
            {
                var rd = ControllerContext.ParentActionViewContext.RouteData;
                ViewData["PAction"] = rd.GetRequiredString("action") as string;
                ViewData["PController"] = rd.GetRequiredString("controller") as string;
                //ViewData["ULevel"] = UserLevel;
                return View();
            }
        }
        
        public ActionResult Logout()
        {
            var cookie = new HttpCookie("Login", "");
            Response.SetCookie(cookie);
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Login()
        {
            try
            {
                var info = Auth.Clients.First().GetUserInfo(Request.QueryString);
                if (info == null) { return RedirectToAction("Authorization", "Error"); }
                User = sqlRepository.CreateOrUpdateUser(info);
                if (User == null) return RedirectToAction("Authorization", "Error");
                return RedirectToAction("Index", "Home"); ;
            }
            catch (Exception e)
            {
                return RedirectToAction("Authorization", "Error");
            }
        }

        public ActionResult ViewAdd(int Id)
        {
            sqlRepository.AddView(Id, User.Id);
            return Redirect(Request.UrlReferrer.ToString());
        }

        public ActionResult ViewRemove(int Id)
        {
            sqlRepository.RemoveView(Id, User.Id);
            return Redirect(Request.UrlReferrer.ToString());
        }

        public ActionResult ViewUpdate(int Id,int Value)
        {
            sqlRepository.UpdateView(Id, User.Id, Value);
            return Redirect(Request.UrlReferrer.ToString());
        }

        public ActionResult ViewSetStar(int Id)
        {
            sqlRepository.UpdateViewStar(Id, User.Id);
            return Redirect(Request.UrlReferrer.ToString());
        }

        public ActionResult ShortView(int Id)
        {
            var view = sqlRepository.GetViewDetails(Id, User.Id);
            if (view == null) return View();
            view.Role = UserRole;
            return View(view);
        }

        public ActionResult LongView(int Id)
        {
            var view = sqlRepository.GetViewDetails(Id, User.Id);
            if (view == null) return View();
            view.Role = UserRole;
            return View(view);
        }
    }
}

AniLiteWebSite/Views/Helper/AuthWidget.cshtml
@model AniLiteWebSite.Core.DataBase.Model.User

@{
    Layout = null;
}

@if (Model == null)
{
    <li>
        <div class="navbar-form">
            <a href="@ViewData["AuthURI"].ToString()" class="btn btn-danger">Вход через Google</a>
        </div>
    </li>
}else{
    <li>
        <div class="navbar-form">
            <a style="padding: 0px 12px !important;" 
               href="@Url.Action("Index", "Profile")" 
               class="@(ViewData["PController"].ToString().ToLower().Equals("profile") ? "btn btn-info" : "btn btn-success")">
                @if (Model.AvatarURI.IsEmpty())
                {
                    <img height="32" src="http://forums.imore.com/avatars/vb_im/avatar153128_1.gif" class="img-circle" />
                    @(Model.FirstName + " " + Model.SecondName)
                }
                else
                {
                    <img height="32" src="@Model.AvatarURI" class="img-circle" />
                    @(Model.FirstName + " " + Model.SecondName)
                }
            </a>
        </div>
    </li>
    <li>
        <div class="navbar-form">
            @Html.ActionLink("Выйти", "Logout", "Helper", new { @class = "btn btn-danger" })
        </div>
    </li>
}

AniLiteWebSite/Views/Helper/LongView.cshtml
@model AniLiteWebSite.Models.ViewDetails

@{
    Layout = null;
}

<td class="row">
    <div class="col-md-2 col-sm-2">
        <a href="@Url.Action("Details","Product", new { id = @Model.ProductId })" class="img-thumbnail">
            <img src="@Model.AvatarURI" style="max-height:64px;max-width:64px">
        </a>
        </div>
        <div class="col-md-10 col-sm-10">
            <b>[@Model.Year] @Model.Names.First()</b>@foreach (var name in Model.Names.Skip(1))
            {
                @(", " + name)
            }
            <br />
            @Model.Reminder
        </div>
</td>

<td class="table-td-middle">
    <div class="row">
        <div class="col-md-3 col-sm-3">
            <a href="@Model.FromURI"><img style="max-height:64px;max-width:64px" src="@Model.PosterFromURI" alt="Источник информации" /></a>
        </div>
        @if (Model.ViewId == 0)
        {
            <div class="col-md-3 col-sm-3">
                <font size="5" color="red"> 0/@Model.MaxEpisode </font>
            </div>
            <div class="col-md-6 col-sm-6">
                <a href="@Url.Action("ViewAdd", "Helper", new { Id = Model.ProductId })" class="btn btn-success">
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Смотреть
                </a>
                <a href="/Product/Details/1" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-info-sign"></span></a>
            </div>
        }
        else
        {
            if (Model.CurrentEpisode >= Model.MaxEpisode)
            {
                <div class="col-md-3 col-sm-3">
                    <font size="5" color="green"> @Model.CurrentEpisode/@Model.MaxEpisode </font>
                </div>
                <div class="col-md-6 col-sm-6">
                    <a href="@Url.Action("ViewUpdate", "Helper", new { Id = Model.ViewId,Value = -1 })" class="btn btn-danger"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></a>
                    <a href="/Product/Details/1" class="btn btn-info"><span class="glyphicon glyphicon-info-sign"></span></a>
                    <a href="#" class="btn btn-warning"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                    <a href="#" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
                    <a href="@Url.Action("ViewSetStar", "Helper", new { Id = Model.ViewId })" class="btn @(Model.Star ? "btn-info" : "btn-default")"><span class="glyphicon @(Model.Star ? "glyphicon-star" : "glyphicon-star-empty")"></span> </a>
                </div>
            }
            else if (Model.CurrentEpisode != 0)
            {
                <div class="col-md-3 col-sm-3">
                    <font size="5" color="blue"> @Model.CurrentEpisode/@Model.MaxEpisode </font>
                </div>
                <div class="col-md-6 col-sm-6">
                    <a href="@Url.Action("ViewUpdate", "Helper", new { Id = Model.ViewId,Value = -1 })" class="btn btn-danger"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></a>
                    <a href="/Product/Details/1" class="btn btn-info"><span class="glyphicon glyphicon-info-sign"></span></a>
                    <a href="#" class="btn btn-warning"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                    <a href="@Url.Action("ViewUpdate", "Helper", new { Id = Model.ViewId, Value = +1 })" class="btn btn-success"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
                    <a href="@Url.Action("ViewSetStar", "Helper", new { Id = Model.ViewId })" class="btn @(Model.Star ? "btn-info" : "btn-default")"><span class="glyphicon @(Model.Star ? "glyphicon-star" : "glyphicon-star-empty")"></span> </a>
                </div>
            }
            else
            {
                <div class="col-md-3 col-sm-3">
                    <font size="5" color="blue"> @Model.CurrentEpisode/@Model.MaxEpisode </font>
                </div>
                <div class="col-md-6 col-sm-6">
                    <a href="#" class="btn btn-default"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></a>
                    <a href="/Product/Details/1" class="btn btn-info"><span class="glyphicon glyphicon-info-sign"></span></a>
                    <a href="#" class="btn btn-warning"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                    <a href="@Url.Action("ViewUpdate", "Helper", new { Id = Model.ViewId, Value = +1 })" class="btn btn-success"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
                    <a href="@Url.Action("ViewSetStar", "Helper", new { Id = Model.ViewId })" class="btn @(Model.Star ? "btn-info" : "btn-default")"><span class="glyphicon @(Model.Star ? "glyphicon-star" : "glyphicon-star-empty")"></span> </a>
                </div>
            }
        }
    </div>
</td>

AniLiteWebSite/Views/Helper/MainMenu.cshtml
@{
    Layout = null;
}

<li class="@(  ViewData["PController"].ToString().ToLower().Equals("product") ? "dropdown active" : "dropdown")">
    @Html.ActionLink("База данных", "Index", "Product")
</li>

<li class="@(  ViewData["PController"].ToString().ToLower().Equals("tracker") ? "dropdown active" : "dropdown")">
    @Html.ActionLink("Обратная связь", "Index", "Tracker")
</li>

AniLiteWebSite/Views/Helper/ShortView.cshtml
@model AniLiteWebSite.Models.ViewDetails
@{
    Layout = null;
}
<div class="row">
    @if (Model.ViewId == 0)
    {
        <div class="col-sm-6 col-md-6">
            <font size="5" color="red">Серий просмотренно 0!</font>
        </div>
        <div class="col-sm-6 col-md-6">
            <a href="@Url.Action("ViewAdd", "Helper", new { Id = Model.ProductId })" class="btn btn-success">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Смотреть
            </a>
        </div>
    }
    else
    {
        if (Model.CurrentEpisode >= Model.MaxEpisode)
        {
            <div class="col-sm-6 col-md-6">
                <font size="5" color="green">Серий просмотренно @Model.CurrentEpisode/@Model.MaxEpisode</font>
            </div>
            <div class="col-sm-6 col-md-6">
                <a href="@Url.Action("ViewUpdate", "Helper", new { Id = Model.ViewId,Value = -1 })" class="btn btn-danger"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></a>
                <a href="#" class="btn btn-warning"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                <a href="#" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
                <a href="@Url.Action("ViewSetStar", "Helper", new { Id = Model.ViewId })" class="btn @(Model.Star ? "btn-info" : "btn-default")"><span class="glyphicon @(Model.Star ? "glyphicon-star" : "glyphicon-star-empty")"></span> </a>
            </div>
        }
        else if(Model.CurrentEpisode!=0)
        {
            <div class="col-sm-6 col-md-6">
                <font size="5" color="blue">Серий просмотренно @Model.CurrentEpisode/@Model.MaxEpisode</font>
            </div>
            <div class="col-sm-6 col-md-6">
                <a href="@Url.Action("ViewUpdate", "Helper", new { Id = Model.ViewId, Value = -1 })" class="btn btn-danger"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></a>
                <a href="#" class="btn btn-warning"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                <a href="@Url.Action("ViewUpdate", "Helper", new { Id = Model.ViewId, Value = +1 })" class="btn btn-success"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
                <a href="@Url.Action("ViewSetStar", "Helper", new { Id = Model.ViewId })" class="btn @(Model.Star ? "btn-info" : "btn-default")"><span class="glyphicon @(Model.Star ? "glyphicon-star" : "glyphicon-star-empty")"></span> </a>
            </div>
        }
        else
        {
            <div class="col-sm-6 col-md-6">
                <font size="5" color="blue">Серий просмотренно @Model.CurrentEpisode/@Model.MaxEpisode</font>
            </div>
            <div class="col-sm-6 col-md-6">
                <a href="#" class="btn btn-default"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></a>
                <a href="#" class="btn btn-warning"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                <a href="@Url.Action("ViewUpdate", "Helper", new { Id = Model.ViewId, Value = +1 })" class="btn btn-success"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
                <a href="@Url.Action("ViewSetStar", "Helper", new { Id = Model.ViewId })" class="btn @(Model.Star ? "btn-info" : "btn-default")"><span class="glyphicon @(Model.Star ? "glyphicon-star" : "glyphicon-star-empty")"></span> </a>
            </div>
        }
    }
</div>